Graphcis Framework: enPerspectiveFreeCamera Class Reference
enPerspectiveFreeCamera Class Reference final
: this is a perspective camera
#include <enPerspectiveFreeCamera.h>
Public Member Functions
enErrorCode init (const sPerspectiveCameraDesc &descriptor)
: used to initialize the camera with user defined values
void TranslateRelative (float x, float y, float z)
: move the camera relative to it's own directions(aka 'up' , 'front' ,'right')
void rotateInYaw (float angleInDegs)
void rotateInPitch (float angleInDegs)
void rotateInRoll (float angleInDegs)
void rotateVector (const enVector2 &rotationDir, float deltaTime=0.01666f)
virtual bool initDefault () override
: give the camera some default settings
void updateDimensions (float newWidth, float newHeight) override
: updates the matrices of the cameras
Public Member Functions inherited from BasePerspectiveCamera
enMatrix4x4 getView () const
enMatrix4x4 getProjection () const
enVector3 getPosition () const
enVector3 getViewPosition () const
enVector3 getUpDir () const
enVector3 getFront () const
enVector3 getRight () const
float getFov () const
float getHeight () const
float getWidth () const
float getFar () const
float getNear () const
float getHorizontalAngle () const
float getVerticalAngle () const
float getZAngle () const
float getSpeed () const
void setViewMatrix (const enMatrix4x4 &matrix)
:set the view matrix
void setProjectionMatrix (const enMatrix4x4 &matrix)
:set the projection matrix
void setPosition (float x, float y, float z)
:sets the position of the camera
void setPosition (const enVector4 &newPosition)
:sets the position of the camera
void setViewPosition (float x, float y, float z)
:sets the view position of the camera
void setViewPosition (const enVector3 &newPosition)
:sets the view position of the camera
void setUpDir (float x, float y, float z)
:sets the 'up' direction of the camera
void setUpDir (const enVector3 &newUp)
:sets the 'up' direction of the camera
void setFront (float x, float y, float z)
:sets the 'front' direction of the camera
void setFront (const enVector3 &newFront)
:sets the 'front' direction of the camera
void setRight (float x, float y, float z)
:sets the 'front' direction of the camera
void setRight (const enVector3 &newRight)
:sets the 'front' direction of the camera
void setHeight (float newHeight)
:sets the 'height' direction of the camera
void setWidth (float newWidth)
:sets the 'width' direction of the camera
void setFar (float newFar)
: the 'm_near' variable
void setNear (float newNear)
: the 'm_near' variable
void setHorzantalAngleDeg (float newAngleInDegrees)
: set the horizontal angle in degrees
void setHorzantalAngleRad (float newAngleInRadians)
: set the horizontal angle in radians
void setVerticalAngleDeg (float newAngleInDegrees)
: set the vertical angle in degrees
void setVerticalAngleRad (float newAngleInRadians)
: set the vertical angle in radians
void setZAngleDeg (float newAngleInDegrees)
: set the Z axis angle in degrees
void setZAngleRad (float newAngleInRadians)
: set the Z axis angle in radians
void setSpeed (float newSpeed)
:sets how fast the camera is.
Private Member Functions
void updateMatrixes ()
:this function updates both the perspective and view matrix
Additional Inherited Members
Protected Attributes inherited from BasePerspectiveCamera
enMatrix4x4 m_view
: represent the following , where the camera is, how it's rotated .
enMatrix4x4 m_projection
: represent
enVector3 m_position
: represent where the camera is in world space(equivalent to eye).
enVector3 m_lookAt
: represent WHERE the camera is looking (equivalent to At).
enVector3 m_up
: it's the direction that represents 'up' relative to the camera
enVector3 m_front
:it's the direction that the camera is pointing too.
enVector3 m_right
:it's the direction that's to the cameras right
float m_fov { 1.04719f }
: used to control how wide the 'lens' of the camera is.
float m_height
: determines the height of the projection
float m_width
: determines the width of the projection
float m_far
: determines how far an object can get before it ignores the object.
float m_near
: determines how close an object can get before it ignores the object.
float m_horizantalAngle
:
float m_verticalAngle
float m_zAngle
float m_speed { 10.0f }
: used to control how fast the camera moves in world-space.
Detailed Description
: this is a perspective camera
Definition at line 43 of file enPerspectiveFreeCamera.h.
Member Function Documentation
init()
enErrorCode enPerspectiveFreeCamera::init (const sPerspectiveCameraDesc & descriptor)
: used to initialize the camera with user defined values
Parameters
descriptor[in] used to give the camera user defined values
Definition at line 10 of file enPerspectiveFreeCamera.cpp.
 {
   m_position = descriptor.position;
   m_lookAt = descriptor.lookAtPosition;
   m_up = descriptor.upDir;
   m_fov = descriptor.fov;
   m_height = descriptor.height;
   m_width = descriptor.width;
   m_horizantalAngle = descriptor.horizantalAngle;
   m_verticalAngle = descriptor.verticalAngle;
   m_zAngle = descriptor.zAngle;
   this->updateMatrixes();
   return enErrorCode::NoError;
 }
References sPerspectiveCameraDesc::fov, sPerspectiveCameraDesc::height, sPerspectiveCameraDesc::lookAtPosition, BasePerspectiveCamera::m_fov, BasePerspectiveCamera::m_height, BasePerspectiveCamera::m_horizantalAngle, BasePerspectiveCamera::m_lookAt, BasePerspectiveCamera::m_position, BasePerspectiveCamera::m_up, BasePerspectiveCamera::m_width, sPerspectiveCameraDesc::position, updateMatrixes(), sPerspectiveCameraDesc::upDir, and sPerspectiveCameraDesc::width.
initDefault()
bool enPerspectiveFreeCamera::initDefault () override virtual
: give the camera some default settings
Bug:
: no known bugs.
Implements BasePerspectiveCamera.
Definition at line 86 of file enPerspectiveFreeCamera.cpp.
 {
   sPerspectiveCameraDesc defaultValues;
   m_position = defaultValues.position;
   m_lookAt = defaultValues.lookAtPosition;
   m_up = defaultValues.upDir;
   m_fov = defaultValues.fov;
   m_height = defaultValues.height;
   m_width = defaultValues.width;
   m_horizantalAngle = defaultValues.horizantalAngle;
   m_verticalAngle = defaultValues.verticalAngle;
   this->updateMatrixes();
   return true;
 }
References sPerspectiveCameraDesc::fov, sPerspectiveCameraDesc::height, sPerspectiveCameraDesc::lookAtPosition, BasePerspectiveCamera::m_fov, BasePerspectiveCamera::m_height, BasePerspectiveCamera::m_horizantalAngle, BasePerspectiveCamera::m_lookAt, BasePerspectiveCamera::m_position, BasePerspectiveCamera::m_up, BasePerspectiveCamera::m_width, sPerspectiveCameraDesc::position, updateMatrixes(), sPerspectiveCameraDesc::upDir, and sPerspectiveCameraDesc::width.
TranslateRelative()
void enPerspectiveFreeCamera::TranslateRelative (float x, float y, float z)
: move the camera relative to it's own directions(aka 'up' , 'front' ,'right')
Parameters
x [in] how much in 'x' to translate
y [in] how much in 'y' to translate
z [in] how much in 'z' to translate
Definition at line 29 of file enPerspectiveFreeCamera.cpp.
 {
   m_position += -m_right * x;
   //m_lookAt += m_right * x;
   m_position += m_up * y;
   //m_lookAt += m_up * y;
   m_position += m_front * z;
   //m_lookAt += m_front * z;
   updateMatrixes();
 }
References BasePerspectiveCamera::m_front, BasePerspectiveCamera::m_position, BasePerspectiveCamera::m_right, BasePerspectiveCamera::m_up, and updateMatrixes().
updateDimensions()
void enPerspectiveFreeCamera::updateDimensions (float newWidth, float newHeight) override virtual
: updates the matrices of the cameras
Bug:
: no known bugs.
Implements BasePerspectiveCamera.
Definition at line 78 of file enPerspectiveFreeCamera.cpp.
 {
   m_width = newWidth;
   m_height = newHeight;
   this->updateMatrixes();
 }
References BasePerspectiveCamera::m_height, BasePerspectiveCamera::m_width, and updateMatrixes().
updateMatrixes()
void enPerspectiveFreeCamera::updateMatrixes () private
:this function updates both the perspective and view matrix
Bug:
: no know bugs
Definition at line 108 of file enPerspectiveFreeCamera.cpp.
 {
   m_front = enVector3
   (
     std::cosf(m_verticalAngle) * std::sinf(m_horizantalAngle),
     std::sinf(m_verticalAngle),
     std::cosf(m_verticalAngle) * std::cosf(m_horizantalAngle)
   );
   m_right = enVector3
   (
     std::sinf(m_horizantalAngle - (glm::pi<float>() / 2)),
     0.0f,
     std::cosf(m_horizantalAngle - (glm::pi<float>() / 2))
   );
   m_up = glm::normalize(glm::cross(m_front, m_right));
   m_projection = glm::perspectiveFovLH(m_fov, m_width, m_height, m_near, m_far);
   m_view = glm::lookAtLH(m_position, m_position + m_front, m_up);
   glm::mat4x4 zRotation(1.0f);
   const enVector4 FirstRow(std::cosf(m_zAngle), -std::sinf(m_zAngle), 0.0f, 0.0f);
   const enVector4 secondRow(std::sinf(m_zAngle), std::cosf(m_zAngle), 0.0f, 0.0f);
   zRotation = glm::row(zRotation, 0, FirstRow);
   zRotation = glm::row(zRotation, 1, secondRow);
   m_view *= zRotation;
 }
References BasePerspectiveCamera::m_far, BasePerspectiveCamera::m_fov, BasePerspectiveCamera::m_front, BasePerspectiveCamera::m_height, BasePerspectiveCamera::m_horizantalAngle, BasePerspectiveCamera::m_near, BasePerspectiveCamera::m_position, BasePerspectiveCamera::m_projection, BasePerspectiveCamera::m_right, BasePerspectiveCamera::m_up, BasePerspectiveCamera::m_view, and BasePerspectiveCamera::m_width.
The documentation for this class was generated from the following files:
C:/Users/Y_Here/Git Repositorios/Graficas Framework [current]/Graphcis_Framework_Neon/Graphcis_Framework_Neon/include/enPerspectiveFreeCamera.h
C:/Users/Y_Here/Git Repositorios/Graficas Framework [current]/Graphcis_Framework_Neon/Graphcis_Framework_Neon/src/enPerspectiveFreeCamera.cpp