Graphcis Framework: appGraphics Class Reference
appGraphics Class Reference
: Takes care of all graphics related operation.
#include <appGraphics.h>
Public Member Functions
virtual bool init () override
: where all resource are gathered and classes are initialized
virtual int run () override
: this is where the main application starts after gathering resources
virtual void destroy () override
: used for freeing resources
Public Attributes
sHardWareInfo m_hardwareInfo
HMODULE m_moduleInstance = nullptr
std::unique_ptr< enSwapChain > m_swapchain = nullptr
std::unique_ptr< enWindow > m_window = nullptr
std::unique_ptr< enDepthStencilView > m_depthStencilView = nullptr
std::unique_ptr< enRenderTargetView > m_renderTargetView = nullptr
std::unique_ptr< enPixelShader > m_pixelShader = nullptr
std::unique_ptr< enVertexShader > m_vertexShader = nullptr
std::unique_ptr< enInputLayout > m_inputLayout = nullptr
std::unique_ptr< enViewport > m_viewport = nullptr
std::unique_ptr< enVertexBuffer > m_vertexBuffer = nullptr
std::unique_ptr< enIndexBuffer > m_indexBuffer = nullptr
std::unique_ptr< enConstBuffer > m_worldMatrix = nullptr
std::unique_ptr< enSampler > m_sampler = nullptr
std::unique_ptr< enModel > m_model = nullptr
std::unique_ptr< enMultiviewTexture > m_renderTargetAndShaderResource = nullptr
std::shared_ptr< enShaderResourceView > m_resourceView = nullptr
glm::mat4x4 m_World = glm::mat4x4(1.0f)
std::vector< enConstBuffer * > m_ConstBufferContainer
glm::vec4 m_MeshColor = glm::vec4(0.7f, 0.7f, 0.7f, 1.0f)
const std::filesystem::path m_initPath = std::filesystem::current_path()
Static Public Attributes
static std::unique_ptr< imGuiManager > m_gui = make_unique<imGuiManager>()
static enConstBuffer * s_ViewMatrixBuffer = nullptr
static enConstBuffer * s_ProjectionMatrixBuffer = nullptr
static enPerspectiveFreeCamera * s_Camera = nullptr
static enFirstPersonCamera * s_FirstPersonCamera = nullptr
static enCameraManager * s_CameraManager = nullptr
static bool s_initIsFinish = false
static bool s_useFreeCam = true
Private Member Functions
bool InitStatics ()
: initializes all static classes.
bool initModules ()
: initializes all modules classes.
enErrorCode initApi ()
: starts the api.
bool createMyClasses ()
: creates all the classes .
bool initContainers ()
: where all the container
HRESULT initForRender ()
: prepares the app for rendering
HRESULT InitWindow (HINSTANCE hInstance, int nCmdShow)
: creates a window
void setShaderAndBuffers ()
: sets the shader and buffers.
void drawWithSeletecRenderTarget (size_t renderTargetIndex)
: draws the scene with the selected
void switchCamera ()
: switches cameras.
void Render ()
: takes care of rendering the image to the screen.
void Update ()
: where each class performs it own update.
Static Private Member Functions
static LRESULT CALLBACK WndProcRedirect (HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
: used to capture the wndProc Events
Detailed Description
: Takes care of all graphics related operation.
Bug:
: no known bugs.
Definition at line 40 of file appGraphics.h.
Member Function Documentation
createMyClasses()
bool appGraphics::createMyClasses () private
: creates all the classes .
Bug:
: no known bugs.
Definition at line 225 of file appGraphics.cpp.
 {
   try
   {
     m_vertexShader = make_unique<enVertexShader>();
     m_pixelShader = make_unique<enPixelShader>();
     m_vertexBuffer = make_unique<enVertexBuffer>();
     m_indexBuffer = make_unique<enIndexBuffer>();
     m_renderTargetView = make_unique<enRenderTargetView>();
     m_inputLayout = make_unique<enInputLayout>();
     m_depthStencilView = make_unique<enDepthStencilView>();
     m_viewport = make_unique<enViewport>();
     m_worldMatrix = make_unique<enConstBuffer>();
     m_resourceView = make_shared<enShaderResourceView>();
     m_sampler = make_unique<enSampler>();
     m_swapchain = make_unique<enSwapChain>();
     m_window = make_unique<enWindow>();
     m_model = make_unique<enModel>();
     m_renderTargetAndShaderResource = make_unique<enMultiviewTexture>();
   }
   catch( const std::exception & e )
   {
     std::cerr << e.what() << std::endl;
     return false;
   }
   return true;
 }
destroy()
void appGraphics::destroy () override virtual
: used for freeing resources
Bug:
: no known bugs
Implements cBaseApp.
Definition at line 139 of file appGraphics.cpp.
 {
   CoUninitialize();
   DELETE_PTR(s_Camera);
   DELETE_PTR(s_FirstPersonCamera);
   DELETE_PTR(s_CameraManager);
   DELETE_PTR(s_ViewMatrixBuffer);
   DELETE_PTR(s_ProjectionMatrixBuffer);
   m_ConstBufferContainer.clear();
   enDevice::ShutDown();
   enDeviceContext::ShutDown();
 }
References soModule< enDevice >::ShutDown(), and soModule< enDeviceContext >::ShutDown().
drawWithSeletecRenderTarget()
void appGraphics::drawWithSeletecRenderTarget (size_t renderTargetIndex) private
: draws the scene with the selected
Parameters
[in] renderTargetIndex which render target to use.
Bug:
: no known bugs.
Definition at line 655 of file appGraphics.cpp.
 {
   enRenderTargetView* ptr_renderTarget = nullptr;
   if( renderTargetIndex == 0 )
   {
     ptr_renderTarget = m_renderTargetView.get();
   }
   else if(renderTargetIndex == 1  ){
     ptr_renderTarget = &m_renderTargetAndShaderResource->m_renderView;
   }
   enDeviceContext& deviceContext = enDeviceContext::getInstance();
   deviceContext.OMSetRenderTargets(ptr_renderTarget, m_depthStencilView.get());
   m_model->DrawMeshes(m_ConstBufferContainer);
 }
References soModule< enDeviceContext >::getInstance(), and enDeviceContext::OMSetRenderTargets().
init()
bool appGraphics::init () override virtual
: where all resource are gathered and classes are initialized
Bug:
: no know bugs
Implements cBaseApp.
Definition at line 51 of file appGraphics.cpp.
 {
   BOOL checkIfSucceeded = GetModuleHandleEx(0x00, NULL, &m_moduleInstance);
   if( checkIfSucceeded == FALSE )
     return false;
   /*Initializes the COM library
   this is so I can load images for directX */
   if( FAILED(CoInitializeEx(NULL, COINIT_MULTITHREADED)) )
   {
     return false;
   }
   if( !InitStatics() )
     return false;
   if( !initModules() )
     return false;
   if( !createMyClasses() )
   {
     this->destroy();
     return false;
   }
   if( FAILED(InitWindow(m_moduleInstance, SW_SHOWDEFAULT)) )
   {
     this->destroy();
     return false;
   }
   if( initContainers() == false )
   {
     this->destroy();
     return false;
   }
   if( !EN_SUCCESS(initApi()) )
   {
     this->destroy();
     return false;
   }
   if( initForRender() == S_FALSE )
   {
     this->destroy();
     return false;
   }
   //enVector2 newSize = enVector2(2000, 2000);
   //bool isSuccessful = this->m_swapchain->ResizeSwapChain(*m_window,
   //                                                       *m_renderTargetView,
   //                                                       *m_depthStencilView,
   //                                                       newSize,
   //                                                       *m_viewport);
   //assert(isSuccessful);
   s_initIsFinish = true;
   return true;
 }
References createMyClasses(), destroy(), initApi(), initContainers(), initForRender(), initModules(), InitStatics(), and InitWindow().
initApi()
enErrorCode appGraphics::initApi () private
: starts the api.
Bug:
:
Definition at line 191 of file appGraphics.cpp.
 {
 #if OPENGL
   glewExperimental = true;
   if( glewInit() != GLEW_OK ) {
     assert((true == false) && " failed to start glew");
   }
   cApiComponents::startupShaderPrograms();
   if( !cApiComponents::createProgram(0u) )
   {
     return enErrorCode::FailedCreation;
   }
  appGraphics::SetCallBackFunctions(*m_window);
 #endif // OPENGL
   enErrorCode checkForError = helper::CreateDeviceAndSwapchain(*m_swapchain,
                                                                *m_window,
                                                                m_hardwareInfo);
   if( !m_gui->is_initialized )
   {
     m_gui->Init(*m_window);
   }
   return checkForError;
 }
initContainers()
bool appGraphics::initContainers () private
: where all the container
Bug:
: no known bugs.
Definition at line 261 of file appGraphics.cpp.
 {
   m_ConstBufferContainer.push_back(s_ViewMatrixBuffer);
   m_ConstBufferContainer.push_back(s_ProjectionMatrixBuffer);
   return true;
 }
initForRender()
HRESULT appGraphics::initForRender () private
: prepares the app for rendering
Bug:
: no known bugs
Definition at line 270 of file appGraphics.cpp.
 {
   enDevice& device = enDevice::getInstance();
   enDeviceContext& deviceContext = enDeviceContext::getInstance();
   bool isSuccessful = false;
   HRESULT hr = S_FALSE;
   enVector2 windowSize = helper::getWindowSize(*m_window);
   // Create a render target view
   m_swapchain->ReciveBuckBuffer(*m_renderTargetView);
   isSuccessful = device.CreateRenderTargetView(*m_renderTargetView, 0);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return S_FALSE;
   }
   isSuccessful = device.CreateRenderTargetView(*m_renderTargetView, 1);
  //if( !EN_SUCCESS(m_renderTargetAndShaderResource->CreateRenderTarget(windowSize.x, windowSize.y, enFormats::fR16G16B16A16)) )
  //{
  //  EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
  //  return S_FALSE;
  //}
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return S_FALSE;
   }
   sTextureDescriptor descriptoDepth;
   descriptoDepth.texWidth = windowSize.x;
   descriptoDepth.texHeight = windowSize.y;
   descriptoDepth.CpuAccess = 0;
   descriptoDepth.texFormat = static_cast<int>(enFormats::depthStencil_format);
   descriptoDepth.Usage = enBufferUse::Default;
   descriptoDepth.BindFlags = enBufferBind::DepthStencil;
   descriptoDepth.arraySize = 1;
   isSuccessful = device.CreateTexture2D(descriptoDepth, m_depthStencilView->m_texture);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return S_FALSE;
   }
   sDepthStencilDescriptor DepthStencilDesc;
   DepthStencilDesc.Format = descriptoDepth.texFormat;
   DepthStencilDesc.Dimension = DepthStencilFormat::two_dimention;
   DepthStencilDesc.Mip = 0;
   m_depthStencilView->m_desc = DepthStencilDesc;
   isSuccessful = device.CreateDepthStencilView(*m_depthStencilView);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return S_FALSE;
   }
   deviceContext.OMSetRenderTargets(m_renderTargetView.get(),
                                    m_depthStencilView.get());
                                    //deviceContext.OMSetRenderTargets()
                                    // Setup the viewport
   D3D11_VIEWPORT vp;
   vp.Width = (FLOAT)windowSize.x;
   vp.Height = (FLOAT)windowSize.y;
   vp.MinDepth = 0.0f;
   vp.MaxDepth = 1.0f;
   vp.TopLeftX = 0;
   vp.TopLeftY = 0;
   sViewportDesc viewDescriptor;
   viewDescriptor.width = static_cast<float>(windowSize.x);
   viewDescriptor.height = static_cast<float>(windowSize.y);
   viewDescriptor.maxDepth = 1.0f;
   m_viewport->init(viewDescriptor);
   deviceContext.RSSetViewports(m_viewport.get());
 #if DIRECTX
   constexpr const char* vertexShaderPath = "GraphcisFramework.fx";
 #elif OPENGL
   constexpr const char* vertexShaderPath = "GraphcisFramework.vert";
 #endif // DIRECTX
 {
   enErrorCode vertexShaderCode = m_vertexShader->compileShaderFromFile(vertexShaderPath,
                                                                        "VS",
                                                                        "vs_4_0");
   if( !EN_SUCCESS(vertexShaderCode) )
   {
     EN_LOG_ERROR_WITH_CODE(vertexShaderCode);
     MessageBox(NULL,
                L"The FX file cannot be compiled.  Please run this executable from the directory that contains the FX file.",
                L"Error",
                MB_OK);
     return S_FALSE;
   }
 }
   // Create the vertex shader
   //hr = device.getInterface()->CreateVertexShader(pVSBlob->GetBufferPointer(), pVSBlob->GetBufferSize(), NULL, &m_vertexShader->m_interface);
   isSuccessful = device.CreateVertexShader(*m_vertexShader);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return S_FALSE;
   }
   m_inputLayout->ReadShaderData(*m_vertexShader);
   isSuccessful = device.CreateInputLayout(*m_inputLayout,
                                           *m_vertexShader);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return S_FALSE;
   }
   // Set the input layout
   //p_ImmediateContext->IASetInputLayout(m_inputLayout->getInterface());
   deviceContext.IASetInputLayout(*m_inputLayout);
 #if DIRECTX
   constexpr const char* pixelShaderPath = "GraphcisFramework.fx";
 #elif OPENGL
   constexpr const char* pixelShaderPath = "GraphcisFramework.frag";
 #endif // DIRECTX
  enErrorCode pixelShaderCode = m_pixelShader->compileShaderFromFile(pixelShaderPath,
                                                                     "PS",
                                                                     "ps_4_0");
   if( EN_FAIL(pixelShaderCode) )
   {
     MessageBox(NULL,
                L"The FX file cannot be compiled.  Please run this executable from the directory that contains the FX file.",
                L"Error",
                MB_OK);
     return hr;
   }
   // Create the pixel shader
   isSuccessful = device.CreatePixelShader(*m_pixelShader);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return S_FALSE;
   }
   if( m_model->LoadModelFromFile("ryuko.fbx") == false )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return S_FALSE;
   }
   // Set vertex buffer
   UINT stride = sizeof(SimpleVertex);
   UINT offset = 0;
   deviceContext.IASetVertexBuffers(m_vertexBuffer.get(), 1);
   deviceContext.IASetIndexBuffer(*m_indexBuffer, enFormats::uR16);
   deviceContext.IASetPrimitiveTopology(static_cast<int>(enTopology::TriList));
   // Create the constant buffers
   sBufferDesc viewBuffer;
   viewBuffer.bindFlags = enBufferBind::Const;
   viewBuffer.stride = sizeof(viewMatrix);
   viewBuffer.elementCount = 1;
   viewBuffer.cpuAccess = 0;
   viewBuffer.index = 0;
   s_ViewMatrixBuffer->init(viewBuffer);
   device.CreateConstBuffer(*s_ViewMatrixBuffer);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation)
       return S_FALSE;
   }
   sBufferDesc ProjectionDescriptor;
   ProjectionDescriptor.bindFlags = enBufferBind::Const;
   ProjectionDescriptor.elementCount = 1;
   ProjectionDescriptor.stride = sizeof(projectionMatrix);
   ProjectionDescriptor.index = 1;
   s_ProjectionMatrixBuffer->init(ProjectionDescriptor);
   isSuccessful = device.CreateConstBuffer(*s_ProjectionMatrixBuffer);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation)
       return S_FALSE;
   }
   sBufferDesc worldMatrixDescriptor;
   worldMatrixDescriptor.elementCount = 1;
   worldMatrixDescriptor.stride = sizeof(ConstBufferWorldColor);
   worldMatrixDescriptor.bindFlags = enBufferBind::Const;
   worldMatrixDescriptor.usage = enBufferUse::Default;
   worldMatrixDescriptor.index = 2;
   m_worldMatrix->init(worldMatrixDescriptor);
   isSuccessful = device.CreateConstBuffer(*m_worldMatrix);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation)
       return S_FALSE;
   }
   m_resourceView->init();
   // Load the Texture
   isSuccessful = device.CreateShaderResourceFromFile(*m_resourceView,
                                                      "neon light.jpg");
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return S_FALSE;
   }
   enMultiViewType renderAndShaderView = helper::generateMultiViewType(enMultiViewType::renderTarget |
                                                                       enMultiViewType::shaderResource);
   isSuccessful = m_renderTargetAndShaderResource->CreateAll(windowSize.x,
                                                             windowSize.y,
                                                             enFormats::fR16G16B16A16,
                                                             enBufferUse::Default,
                                                             renderAndShaderView);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return S_FALSE;
   }
   {
     sSamplerDesc samplerDescriptor;
     samplerDescriptor.filter = static_cast<uint32_t>(enFilter::MinMagMip_Linear);
     samplerDescriptor.addressU = static_cast<uint32_t>(enAddress::Wrap);
     samplerDescriptor.addressV = static_cast<uint32_t>(enAddress::Wrap);
     samplerDescriptor.addressW = static_cast<uint32_t>(enAddress::Wrap);
     samplerDescriptor.comparingFunc = static_cast<int>(enComparison::Never);
     samplerDescriptor.minLod = 0.0f;
     samplerDescriptor.maxLod = std::numeric_limits<float>::max();
     samplerDescriptor.AnisotropicLevel = 1u;
     samplerDescriptor.index = 0;
     m_sampler->init(samplerDescriptor);
     isSuccessful = device.CreateSamplerState(*m_sampler);
     if( !isSuccessful )
     {
       EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
       return S_FALSE;
     }
   }
 //************************************//************************************//************************************/************************************/
 //************************************//************************************//************************************/************************************/
   sPerspectiveCameraDesc descriptorCamera;
   descriptorCamera.upDir = enVector3(0.0f, 1.0f, 0.0f);
   descriptorCamera.lookAtPosition = enVector3(0.0f, 0.0f, -1.0f);
   descriptorCamera.position = enVector3(0.0f, 0.0f, -10.0f);
   descriptorCamera.height = windowSize.y;
   descriptorCamera.width = windowSize.x;
   s_Camera->init(descriptorCamera);
   sFirstPersonCameraDesc cameraDescriptor;
   s_FirstPersonCamera->init(cameraDescriptor);
   s_CameraManager->addCamera(s_Camera);
   s_CameraManager->addCamera(s_FirstPersonCamera);
   // Initialize the world matrices
   m_World = glm::identity<glm::mat4x4>();
   // Initialize the view matrix
   glm::vec3 Eye(0.0f, 3.0f, -6.0f);
   glm::vec3 At(0.0f, 0.0f, -1.0f);
   glm::vec3 Up(0.0f, 1.0f, 0.0f);
   viewMatrix cbNeverChanges;
   enMatrix4x4 CameraViewMatrix = s_Camera->getView();
   cbNeverChanges.mView = helper::arrangeForApi(CameraViewMatrix);/* s_Camera.getView()*/
   deviceContext.UpdateSubresource(s_ViewMatrixBuffer, &cbNeverChanges);
   projectionMatrix cbChangesOnResize;
   enMatrix4x4 CameraProjectionMatrix = s_Camera->getProjection();
   cbChangesOnResize.mProjection = helper::arrangeForApi(CameraProjectionMatrix);
   deviceContext.UpdateSubresource(s_ProjectionMatrixBuffer, &cbChangesOnResize);
   for( auto& mesh : m_model->m_meshes )
   {
     mesh.mptr_resource = m_resourceView;
   }
   return S_OK;
 }
References enDevice::CreateDepthStencilView(), enDevice::CreateRenderTargetView(), enDevice::CreateTexture2D(), soModule< enDeviceContext >::getInstance(), soModule< enDevice >::getInstance(), enDeviceContext::IASetIndexBuffer(), enDeviceContext::IASetInputLayout(), enDeviceContext::IASetPrimitiveTopology(), enDeviceContext::IASetVertexBuffers(), enDeviceContext::OMSetRenderTargets(), enDeviceContext::RSSetViewports(), and sTextureDescriptor::Usage.
initModules()
bool appGraphics::initModules () private
: initializes all modules classes.
Bug:
:
Definition at line 179 of file appGraphics.cpp.
 {
   if( enDevice::StartUp(nullptr) == -1 )
     return false;
   if( enDeviceContext::StartUp(nullptr) == -1 )
     return false;
   return true;
 }
References soModule< enDevice >::StartUp(), and soModule< enDeviceContext >::StartUp().
InitStatics()
bool appGraphics::InitStatics () private
: initializes all static classes.
Bug:
: no known bug
Definition at line 158 of file appGraphics.cpp.
 {
   try
   {
     s_Camera = new enPerspectiveFreeCamera();
     s_FirstPersonCamera = new enFirstPersonCamera();
     s_CameraManager = new enCameraManager();
     s_ViewMatrixBuffer = new enConstBuffer();
     s_ProjectionMatrixBuffer = new enConstBuffer();
   }
   catch( const std::bad_alloc & allocError )
   {
     std::cout << allocError.what() << std::endl;
     return false;
   }
   return true;
 }
Render()
void appGraphics::Render () private
: takes care of rendering the image to the screen.
Bug:
: no known bugs.
Definition at line 706 of file appGraphics.cpp.
 {
   static float t = 0.0f;
   enDeviceContext& deviceContext = enDeviceContext::getInstance();
   {
     static DWORD dwTimeStart = 0;
     DWORD dwTimeCur = GetTickCount();
     if( dwTimeStart == 0 )
       dwTimeStart = dwTimeCur;
     t = (dwTimeCur - dwTimeStart) / 1000.0f;
   }
   // Modify the color
   m_MeshColor.x = (sinf(t * 1.0f) + 1.0f) * 0.5f;
   m_MeshColor.y = (cosf(t * 3.0f) + 1.0f) * 0.5f;
   m_MeshColor.z = (sinf(t * 5.0f) + 1.0f) * 0.5f;
   //
   // Clear the back buffer
   //
   //float ClearColor[4] = { 0.0f, 0.125f, 0.3f, 1.0f }; // red, green, blue, alpha
   static sColorf ClearColor{ 0.40f,0.50f,1.00f,1.0f };
   deviceContext.ClearRenderTargetView(m_renderTargetAndShaderResource->m_renderView, &ClearColor);
   //
   // Clear the depth buffer to 1.0 (max depth)
   //
   deviceContext.ClearDepthStencilView(*m_depthStencilView);
   this->setShaderAndBuffers();
   this->drawWithSeletecRenderTarget(1);
 /*+++++++++++++++++++++++++++++++++++++++++++++*/
   this->switchCamera();
   deviceContext.ClearRenderTargetView(*m_renderTargetView);
   //
   // Clear the depth buffer to 1.0 (max depth)
   //
   deviceContext.ClearDepthStencilView(*m_depthStencilView);
   this->setShaderAndBuffers();
   this->drawWithSeletecRenderTarget(0);
 /*+++++++++++++++++++++++++++++++++++++++++++++*/
   this->switchCamera();
   deviceContext.ClearRenderTargetView(m_renderTargetAndShaderResource->m_renderView);
   // Clear the depth buffer to 1.0 (max depth)
   deviceContext.ClearDepthStencilView(*m_depthStencilView);
   this->setShaderAndBuffers();
   this->drawWithSeletecRenderTarget(1);
   this->drawWithSeletecRenderTarget(0);
   ConstBufferWorldColor cb;
   cb.vMeshColor = m_MeshColor;
   cb.mWorld = helper::arrangeForApi(m_World);
   deviceContext.UpdateSubresource(m_worldMatrix.get(), &cb);
   m_gui->beginFrame("camera view");
   m_gui->addImage(*m_renderTargetAndShaderResource->m_shaderResource);
   m_gui->addButton("switch Cam", s_useFreeCam);
   m_gui->endFrame();
   m_swapchain->Present();
 }
References enDeviceContext::ClearDepthStencilView(), drawWithSeletecRenderTarget(), soModule< enDeviceContext >::getInstance(), setShaderAndBuffers(), switchCamera(), and enDeviceContext::UpdateSubresource().
run()
int appGraphics::run () override virtual
: this is where the main application starts after gathering resources
Bug:
: no know bugs
Implements cBaseApp.
Definition at line 115 of file appGraphics.cpp.
 {
   // Main message loop
   MSG msg = { 0 };
   static glm::vec2 windowSize = helper::getWindowSize(*m_window);
   while( WM_QUIT != msg.message )
   {
     //glm::vec2 currentWindowSize = helper::getWindowSize(*m_window);
     if( PeekMessage(&msg, NULL, 0, 0, PM_REMOVE) )
     {
       TranslateMessage(&msg);
       DispatchMessage(&msg);
     }
     else
     {
       this->Render();
       this->Update();
     }
   }
   return (int)msg.wParam;
 }
References Render(), and Update().
setShaderAndBuffers()
void appGraphics::setShaderAndBuffers () private
: sets the shader and buffers.
Bug:
: no known bugs.
Definition at line 635 of file appGraphics.cpp.
 {
   enDeviceContext& deviceContext = enDeviceContext::getInstance();
   deviceContext.VSSetShader(*m_vertexShader);
   deviceContext.VSSetConstantBuffer(*s_ViewMatrixBuffer, s_ViewMatrixBuffer->getIndex());
   deviceContext.VSSetConstantBuffer(*s_ProjectionMatrixBuffer,
                                     s_ProjectionMatrixBuffer->getIndex());
   deviceContext.VSSetConstantBuffer(*m_worldMatrix,
                                     m_worldMatrix->getIndex());
   deviceContext.PSSetShader(*m_pixelShader);
   deviceContext.PSSetConstantBuffers(*m_worldMatrix, m_worldMatrix->getIndex());
   deviceContext.PSSetShaderResources(m_resourceView.get(), 1);
   deviceContext.PSSetSampler(*m_sampler);
 }
References soModule< enDeviceContext >::getInstance(), enDeviceContext::PSSetConstantBuffers(), enDeviceContext::PSSetShader(), enDeviceContext::PSSetShaderResources(), enDeviceContext::VSSetConstantBuffer(), and enDeviceContext::VSSetShader().
switchCamera()
void appGraphics::switchCamera () private
: switches cameras.
Bug:
: no known bugs.
Definition at line 675 of file appGraphics.cpp.
 {
   BasePerspectiveCamera* ptr_camera = nullptr;
   if( s_useFreeCam )
   {
     ptr_camera = s_CameraManager->getFirstPersonCamera();
     s_useFreeCam = false;
   }
   else if( !s_useFreeCam )
   {
     ptr_camera = s_CameraManager->getFreeCamera();
     s_useFreeCam = true;
   }
   enDeviceContext& deviceContext = enDeviceContext::getInstance();
   viewMatrix cbNeverChanges;
   enMatrix4x4 MatrixForCamera = ptr_camera->getView();
   cbNeverChanges.mView = helper::arrangeForApi(MatrixForCamera);
   deviceContext.UpdateSubresource(s_ViewMatrixBuffer, &cbNeverChanges);
   projectionMatrix cbChangesOnResize;
   enMatrix4x4 ProjMatrixForCamera = ptr_camera->getProjection();
   cbChangesOnResize.mProjection = helper::arrangeForApi(ProjMatrixForCamera);
   deviceContext.UpdateSubresource(s_ProjectionMatrixBuffer, &cbChangesOnResize);
 }
References enCameraManager::getFirstPersonCamera(), enCameraManager::getFreeCamera(), soModule< enDeviceContext >::getInstance(), BasePerspectiveCamera::getProjection(), BasePerspectiveCamera::getView(), and enDeviceContext::UpdateSubresource().
Update()
void appGraphics::Update () private
: where each class performs it own update.
Bug:
:no known bugs.
Definition at line 783 of file appGraphics.cpp.
 {
   uint32c heightBeforeUpdate = m_window->getHeight();
   uint32c widthBeforeUpdate = m_window->getWidth();
   m_window->update();
   if( heightBeforeUpdate != m_window->getHeight() ||
      widthBeforeUpdate != m_window->getWidth() )
   {
     uint32c newWidth = m_window->getWidth();
     uint32c newHeight = m_window->getHeight();
     enVector2 const NewSize(newWidth, newHeight);
     m_swapchain->ResizeSwapChain(*m_window,
                                  *m_renderTargetView,
                                  *m_depthStencilView,
                                  NewSize,
                                  *m_viewport);
     enDeviceContext& deviceContext = enDeviceContext::getInstance();
     s_CameraManager->updateCameras(newWidth, newHeight);
     enPerspectiveFreeCamera* ptr_freeCam = s_CameraManager->getFreeCamera();
     viewMatrix ViewMatrixData;
     ViewMatrixData.mView = ptr_freeCam->getView();
     helper::arrangeForApi(ViewMatrixData.mView);
     deviceContext.UpdateSubresource(s_ViewMatrixBuffer, &ViewMatrixData.mView);
     projectionMatrix  projMatrixData;
     projMatrixData.mProjection = ptr_freeCam->getProjection();
     helper::arrangeForApi(projMatrixData.mProjection);
     deviceContext.UpdateSubresource(s_ProjectionMatrixBuffer, &projMatrixData.mProjection);
   }
 }
References enCameraManager::getFreeCamera(), soModule< enDeviceContext >::getInstance(), BasePerspectiveCamera::getProjection(), BasePerspectiveCamera::getView(), enCameraManager::updateCameras(), and enDeviceContext::UpdateSubresource().
WndProcRedirect()
LRESULT appGraphics::WndProcRedirect (HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam) static private
: used to capture the wndProc Events
Bug:
: no known bugs
s_FirstPersonCamera.rotateInYaw(10.0f);
Definition at line 826 of file appGraphics.cpp.
 {
   PAINTSTRUCT ps;
   HDC hdc;
   if( ImGui_ImplWin32_WndProcHandler(hWnd, message, wParam, lParam) )
     return true;
   enDeviceContext& deviceContext = enDeviceContext::getInstance();
   if( s_initIsFinish == false )
   {
     return DefWindowProc(hWnd, message, wParam, lParam);
   }
   BasePerspectiveCamera* cameraPtr = nullptr;
   if( s_useFreeCam )
   {
     cameraPtr = s_CameraManager->getFirstPersonCamera();
   }
   else
   {
     cameraPtr = s_CameraManager->getFreeCamera();
   }
   switch( message )
   {
     case WM_PAINT:
       hdc = BeginPaint(hWnd, &ps);
       EndPaint(hWnd, &ps);
       break;
     case WM_DESTROY:
       PostQuitMessage(0);
       break;
     case WM_KEYDOWN:
     {
       if( wParam == (WPARAM)'1' )
       {
         if( s_useFreeCam )
         {
           s_useFreeCam = false;
           std::cout << "false\n";
         }
         else
         {
           s_useFreeCam = true;
           std::cout << "true\n";
         }
       }
       if( wParam == (WPARAM)'W' )
       {
         if( auto* freeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           freeCam->TranslateRelative(0.0f, 0.0f, 1.0f);
         }
         if( auto* FirstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           FirstPersonCam->TranslateRelative(0.0f, 0.0f, 1.0f);
         }
       }
       if( wParam == (WPARAM)'S' )
       {
         //s_FirstPersonCamera.TranslateRelative(0.0f, 0.0f, -1.0f);
         if( auto* freeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           freeCam->TranslateRelative(0.0f, 0.0f, -1.0f);
         }
         if( auto* firstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           firstPersonCam->TranslateRelative(0.0f, 0.0f, -1.0f);
         }
       }
       if( wParam == (WPARAM)'D' )
       {
         if( auto* FreeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           FreeCam->TranslateRelative(-1.0f, 0.0f, 0.0f);
         }
         if( auto* FirstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           FirstPersonCam->TranslateRelative(-1.0f, 0.0f, 0.0f);
         }
         //s_FirstPersonCamera.TranslateRelative(-1.0f, 0.0f, 0.0f);
       }
       if( wParam == (WPARAM)'A' )
       {
        // s_FirstPersonCamera.TranslateRelative(1.0f, 0.0f, 0.0f);
         if( auto* freeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           freeCam->TranslateRelative(1.0f, 0.0f, 0.0f);
         }
         if( auto* FirstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           FirstPersonCam->TranslateRelative(1.0f, 0.0f, 0.0f);
         }
       }
       if( wParam == static_cast<WPARAM>('E') )
       {
         //s_FirstPersonCamera.TranslateRelative(0.0f, 1.0f, 0.0f);
         if( auto* freeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           freeCam->TranslateRelative(0.0f, 1.0f, 0.0f);
         }
         if( auto* FirstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           FirstPersonCam->TranslateRelative(0.0f, 1.0f, 0.0f);
         }
       }
       if( wParam == static_cast<WPARAM>('Q') )
       {
         //s_FirstPersonCamera.TranslateRelative(0.0f, -1.0f, 0.0f);
         if( auto* freeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           freeCam->TranslateRelative(0.0f, -1.0f, 0.0f);
         }
         if( auto* FirstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           FirstPersonCam->TranslateRelative(0.0f, -1.0f, 0.0f);
         }
       }
       if( wParam == VK_RIGHT )
       {
         if( auto* FreeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           FreeCam->rotateInYaw(-10.0f);
         }
         if( auto* FirstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           FirstPersonCam->rotateInYaw(-10.0f);
         }
       }
       if( wParam == VK_LEFT )
       {
         if( auto* FreeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           FreeCam->rotateInYaw(10.0f);
         }
         if( auto* FirstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           FirstPersonCam->rotateInYaw(10.0f);
         }
       }
       if( wParam == VK_UP )
       {
         if( auto* freeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           freeCam->rotateInPitch(-10.0f);
         }
         if( auto* FirstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           FirstPersonCam->rotateInPitch(-10.0f);
         }
         //s_FirstPersonCamera.rotateInPitch(-10.0f);
       }
       if( wParam == VK_DOWN )
       {
         //s_FirstPersonCamera.rotateInPitch(10.0f);
         if( auto* FreeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           FreeCam->rotateInPitch(10.0f);
         }
         if( auto* FirstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           FirstPersonCam->rotateInPitch(10.0f);
         }
       }
       if( wParam == static_cast<WPARAM>('I') )
       {
         //s_FirstPersonCamera.rotateInRoll(10.0f);
         if( auto* freeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           freeCam->rotateInRoll(10.0f);
         }
         if( auto* FirstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           FirstPersonCam->rotateInRoll(10.0f);
         }
       }
       if( wParam == static_cast<WPARAM>('O') )
       {
         //s_FirstPersonCamera.rotateInRoll(-10.0f);
         if( auto* freeCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           freeCam->rotateInRoll(-10.0f);
         }
         if( auto* FirstPersonCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           FirstPersonCam->rotateInRoll(-10.0f);
         }
       }
       viewMatrix cbNeverChanges;
       cbNeverChanges.mView = glm::transpose(cameraPtr->getView());
       deviceContext.UpdateSubresource(s_ViewMatrixBuffer, &cbNeverChanges);
       projectionMatrix cbChangesOnResize;
       cbChangesOnResize.mProjection = glm::transpose(cameraPtr->getProjection());
       deviceContext.UpdateSubresource(s_ProjectionMatrixBuffer, &cbChangesOnResize);
     }
     break;
     case(WM_MOUSEMOVE):
     {
       if( wParam & MK_SHIFT )
       {
         WINDOWINFO windInfo;
         windInfo.cbSize = sizeof(WINDOWINFO);
         GetWindowInfo(hWnd, &windInfo);
         const int32_t WindowLocationX = (windInfo.rcWindow.right - windInfo.rcWindow.left);
         const int32_t WindowLocationY = (windInfo.rcWindow.bottom - windInfo.rcWindow.top);
         POINT  currentPos;
         GetCursorPos(&currentPos);
         SetCursorPos(WindowLocationX * .5f,
                      WindowLocationY * .5f);
         enVector3 mouseDir(currentPos.x - (WindowLocationX * .5f),
                            currentPos.y - (WindowLocationY * .5f),
                            0.0f);
         mouseDir.x = -mouseDir.x;
         if( auto* FirstPersonCam = dynamic_cast<enPerspectiveFreeCamera*>(cameraPtr) )
         {
           FirstPersonCam->rotateVector(mouseDir);
         }
         if( auto* freeCam = dynamic_cast<enFirstPersonCamera*>(cameraPtr) )
         {
           freeCam->rotateVector(mouseDir);
         }
         viewMatrix cbNeverChanges;
         cbNeverChanges.mView = cameraPtr->getView();
         helper::arrangeForApi(cbNeverChanges.mView);
         deviceContext.UpdateSubresource(s_ViewMatrixBuffer, &cbNeverChanges);
         projectionMatrix cbChangesOnResize;
         cbChangesOnResize.mProjection = cameraPtr->getProjection();
         helper::arrangeForApi(cbChangesOnResize.mProjection);
         deviceContext.UpdateSubresource(s_ProjectionMatrixBuffer, &cbChangesOnResize);
       }
     }
     break;
     default:
       return DefWindowProc(hWnd, message, wParam, lParam);
   }
   return 0;
 }
References enCameraManager::getFirstPersonCamera(), enCameraManager::getFreeCamera(), soModule< enDeviceContext >::getInstance(), BasePerspectiveCamera::getProjection(), BasePerspectiveCamera::getView(), and enDeviceContext::UpdateSubresource().
The documentation for this class was generated from the following files:
C:/Users/Y_Here/Git Repositorios/Graficas Framework [current]/Graphcis_Framework_Neon/Graphcis_Framework_Neon/include/appGraphics.h
C:/Users/Y_Here/Git Repositorios/Graficas Framework [current]/Graphcis_Framework_Neon/Graphcis_Framework_Neon/src/appGraphics.cpp