Graphcis Framework: enMultiviewTexture Class Reference
enMultiviewTexture Class Reference
: create 1 texture that can be used by both depth-stencil View and Render-target View.
#include <enMultiviewTexture.h>
Public Member Functions
enErrorCode CreateDepthStencil (float width, float height, int Format)
: creates a depth-stencil-view.
enErrorCode CreateRenderTarget (float width, float height, int Format)
: creates a render-target-view.
enErrorCode CreateShaderResource (float width, float height, int Format)
: creates a shader-resource-view.
bool CreateAll (float width, float height, int format, enBufferUse usage, enMultiViewType typeOfView)
bool setRenderTarget ()
bool setDepthStencil ()
Public Attributes
enDepthStencilView m_depthView
: the depth Stencil View.
enRenderTargetView m_renderView
: the render-target view.
std::shared_ptr< enShaderResourceView > m_shaderResource = std::make_shared<enShaderResourceView>()
:
Private Member Functions
enBufferBind getBindingFlagsBasedOnMyType ()
bool CreateTexture (enMultiViewType type, float width, float height)
: Create a texture that made with a certain view in mind.
enMultiViewType getType () const
Private Attributes
enTexture2D m_sharedTexture
: the textured used by both the renderTarget and DepthStencil.
enMultiViewType m_type = enMultiViewType::zeroType
: used to keep track of which of the view is being used.
Detailed Description
: create 1 texture that can be used by both depth-stencil View and Render-target View.
Bug:
: no known bugs.
Definition at line 15 of file enMultiviewTexture.h.
Member Function Documentation
CreateDepthStencil()
enErrorCode enMultiviewTexture::CreateDepthStencil (float width, float height, int Format)
: creates a depth-stencil-view.
Parameters
[in] width : the width of the texture.
[in] height the height of the texture.
Bug:
: no known bugs.
Definition at line 8 of file enMultiviewTexture.cpp.
 {
   enDevice& device = enDevice::getInstance();
   sDepthStencilDescriptor DepthStencilDesc;
   DepthStencilDesc.Format = Format;
   DepthStencilDesc.Dimension = DepthStencilFormat::two_dimention;
   DepthStencilDesc.Mip = 0;
   m_depthView.m_desc = DepthStencilDesc;
   bool const isSuccessful = device.CreateDepthStencilView(m_depthView,
                                                           m_sharedTexture);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return enErrorCode::FailedCreation;
   }
   return enErrorCode::NoError;
 }
References enDevice::CreateDepthStencilView(), soModule< enDevice >::getInstance(), m_depthView, enDepthStencilView::m_desc, and m_sharedTexture.
CreateRenderTarget()
enErrorCode enMultiviewTexture::CreateRenderTarget (float width, float height, int Format)
: creates a render-target-view.
Parameters
[in] width : the width of the texture.
[in] height the height of the texture.
Bug:
: no known bugs.
Definition at line 34 of file enMultiviewTexture.cpp.
 {
   enDevice& device = enDevice::getInstance();
   sRenderTargetDesc2D renderTargetDesc;
   renderTargetDesc.format = Format;
   renderTargetDesc.renderTargetType = enRenderTargetViewType::renderTarget2D;
   renderTargetDesc.mip = 0;
   bool const isSuccessful = device.CreateRenderTargetView(m_renderView,
                                                           m_sharedTexture,
                                                           renderTargetDesc);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return enErrorCode::FailedCreation;
   }
   return enErrorCode::NoError;
 }
References enDevice::CreateRenderTargetView(), soModule< enDevice >::getInstance(), m_renderView, and m_sharedTexture.
CreateShaderResource()
enErrorCode enMultiviewTexture::CreateShaderResource (float width, float height, int Format)
: creates a shader-resource-view.
Parameters
[in] width : the width of the texture.
[in] height the height of the texture.
Bug:
: no known bugs.
Definition at line 60 of file enMultiviewTexture.cpp.
 {
   enDevice& device = enDevice::getInstance();
   bool const isSuccessful = device.CreateShaderResourceFromTexture(*m_shaderResource,
                                                                    m_sharedTexture);
   if( !isSuccessful )
   {
     EN_LOG_ERROR_WITH_CODE(enErrorCode::FailedCreation);
     return enErrorCode::FailedCreation;
   }
   return  enErrorCode::NoError;
 }
References enDevice::CreateShaderResourceFromTexture(), soModule< enDevice >::getInstance(), m_shaderResource, and m_sharedTexture.
CreateTexture()
bool enMultiviewTexture::CreateTexture (enMultiViewType type, float width, float height) private
: Create a texture that made with a certain view in mind.
Parameters
[in] type controls which type of texture is going to be made.
[in] width the width of the texture.
[in] height the height of the texture.
Definition at line 177 of file enMultiviewTexture.cpp.
 {
   enDevice& device = enDevice::getInstance();
   bool isSuccessful = false;
   switch( type )
   {
     case zeroType:
       break;
     case renderTarget:
     {
       sTextureDescriptor renderDesc = helper::generateTextureDescForRenderTarget(width, height);
       isSuccessful = device.CreateTexture2D(renderDesc, this->m_sharedTexture);
       return  isSuccessful;
     }
     case depthStencil:
     {
       sTextureDescriptor depthStencilDesc = helper::generateTextureDescForDepthStencil(width, height);
       isSuccessful = device.CreateTexture2D(depthStencilDesc, this->m_sharedTexture);
       return  isSuccessful;
     }
     default:
       break;
   }
   return false;
 }
References enDevice::CreateTexture2D(), soModule< enDevice >::getInstance(), and m_sharedTexture.
getBindingFlagsBasedOnMyType()
enBufferBind enMultiviewTexture::getBindingFlagsBasedOnMyType () private
Returns
: enBufferBind value, based on which value 'm_type' is.
Definition at line 160 of file enMultiviewTexture.cpp.
 {
   enBufferBind result = enBufferBind::NONE;
   if( m_type & enMultiViewType::renderTarget )
     result = static_cast<enBufferBind> (result | enBufferBind::RenderTarget);
   if( m_type & enMultiViewType::depthStencil )
     result = static_cast<enBufferBind> (result | enBufferBind::DepthStencil);
   if( m_type & enMultiViewType::shaderResource )
     result = static_cast<enBufferBind> (result | enBufferBind::ShaderResource);
   return result;
 }
References m_type.
The documentation for this class was generated from the following files:
C:/Users/Y_Here/Git Repositorios/Graficas Framework [current]/Graphcis_Framework_Neon/Graphcis_Framework_Neon/include/enMultiviewTexture.h
C:/Users/Y_Here/Git Repositorios/Graficas Framework [current]/Graphcis_Framework_Neon/Graphcis_Framework_Neon/src/enMultiviewTexture.cpp