Graphcis Framework: enSwapChain Class Reference
enSwapChain Class Reference
: takes care of switching the front-buffers and back-buffer each frame.
#include <enSwapChain.h>
Public Member Functions
enSwapChain (const enSwapChain &other)=delete
enSwapChain (enSwapChain &&other) noexcept
enSwapChain & operator= (const enSwapChain &other)=delete
enSwapChain & operator= (enSwapChain &&other) noexcept
bool init (const sSwapDesc &descriptor)
: sets up the descriptor for the buffer.
sSwapDesc getSwapChainDesc () const
bool ResizeSwapChain (enWindow &currentWindow, enRenderTargetView &renderTargetView, enDepthStencilView &DepthStencilView, enVector2 const &newSize, enViewport &viewport)
: changes the size of the swap chain.
bool ReciveBuckBuffer (enRenderTargetView &renderTargetView)
: give the swap-chain a back buffer.
void Present (int options=0)
: presents what the back-buffer currently has.
void setWindow (enWindow &window)
: sets which window the swap-chain controls
Public Attributes
sSwapDesc m_descriptor
Detailed Description
: takes care of switching the front-buffers and back-buffer each frame.
Bug:
: no known bugs.
Definition at line 15 of file enSwapChain.h.
Member Function Documentation
getSwapChainDesc()
sSwapDesc enSwapChain::getSwapChainDesc () const
Returns
my descriptor for the swap-chain.
Bug:
: no known bugs.
Definition at line 47 of file enSwapChain.cpp.
 {
   return m_descriptor;
 }
init()
bool enSwapChain::init (const sSwapDesc & descriptor)
: sets up the descriptor for the buffer.
Bug:
: no known bugs.
Definition at line 39 of file enSwapChain.cpp.
 {
   m_descriptor = descriptor;
   return true;;
 }
Present()
void enSwapChain::Present (int options = 0)
: presents what the back-buffer currently has.
Bug:
: no known bugs
Definition at line 164 of file enSwapChain.cpp.
 {
 #if DIRECTX
   m_interface->Present(0,options);
 #elif OPENGL
   glfwSwapBuffers(m_descriptor.outputWindow);
 #endif // DIRECTX
 }
ReciveBuckBuffer()
bool enSwapChain::ReciveBuckBuffer (enRenderTargetView & renderTargetView)
: give the swap-chain a back buffer.
Bug:
:no known bugs
Definition at line 135 of file enSwapChain.cpp.
 {
 #if DIRECTX
   HRESULT hr = m_interface->GetBuffer(0,
                                       __uuidof(ID3D11Texture2D),
                                       (LPVOID*)&renderTargetView.m_targets[0].m_interface);
   if( FAILED(hr) )
     return false;
   else
   {
     renderTargetView.m_usedTargets[0] = true;
     renderTargetView.m_targetsCount++;
   }
   return true;
 #elif OPENGL
   m_GlBackBuffer = &renderTargetView.m_targets[0];
   return true;
 #endif // DIRECTX
   return false;
 }
ResizeSwapChain()
bool enSwapChain::ResizeSwapChain (enWindow & currentWindow, enRenderTargetView & renderTargetView, enDepthStencilView & DepthStencilView, enVector2 const & newSize, enViewport & viewport)
: changes the size of the swap chain.
Bug:
: requires that enDevice and enDeviceContext already be initialized
Definition at line 76 of file enSwapChain.cpp.
 {
   enVector2 const sizeOfWindow = helper::getWindowSize(currentWindow);
   bool isSuccessful = false;
   enDevice& device = enDevice::getInstance();
   enDeviceContext& deviceContext = enDeviceContext::getInstance();
   isSuccessful = renderTargetView.ReleaseAllInterfaces();
   assert(isSuccessful && " Error when Releasing all render-targets and renderTargetView");
   isSuccessful = DepthStencilView.ReleaseAllInterfaces();
   assert(isSuccessful && " Error when Releasing all DepthStencilView interfaces ");
   this->m_descriptor.buffWidth = newSize.x;
   this->m_descriptor.buffHeight = newSize.y;
   sTextureDescriptor const DepthDesc = helper::generateTextureDescForDepthStencil(newSize.x,
                                                                         newSize.y);
   DepthStencilView.m_texture.m_desc = DepthDesc;
 #if DIRECTX
   HRESULT hr = m_interface->ResizeBuffers(0, newSize.x, newSize.y, DXGI_FORMAT_UNKNOWN, 0);
   assert(!FAILED(hr) && " Error when Resizing the swap chain");
 #elif OPENGL
 #endif // DIRECTX
   isSuccessful = this->ReciveBuckBuffer(renderTargetView);
   assert(isSuccessful && " Error with getting a backBuffer for SwapChain");
   isSuccessful = device.CreateRenderTargetView(renderTargetView, 0);
   assert(isSuccessful && " Error with creating a renderTarget");
   isSuccessful = device.CreateTexture2D(DepthStencilView.m_texture.m_desc, DepthStencilView.m_texture);
   assert(isSuccessful && " Error with creating a Stencil");
   isSuccessful = device.CreateDepthStencilView(DepthStencilView);
   assert(isSuccessful && " Error with creating a Depth-Stencil-View ");
   deviceContext.OMSetRenderTargets(&renderTargetView, &DepthStencilView);
   viewport.m_descriptor.width = newSize.x;
   viewport.m_descriptor.height= newSize.y;
   deviceContext.RSSetViewports(&viewport);
   return  isSuccessful;
 }
References enDevice::CreateDepthStencilView(), enDevice::CreateRenderTargetView(), enDevice::CreateTexture2D(), soModule< enDeviceContext >::getInstance(), soModule< enDevice >::getInstance(), enTexture2D::m_desc, enDepthStencilView::m_texture, enDeviceContext::OMSetRenderTargets(), ReciveBuckBuffer(), enRenderTargetView::ReleaseAllInterfaces(), and enDeviceContext::RSSetViewports().
setWindow()
void enSwapChain::setWindow (enWindow & window)
: sets which window the swap-chain controls
Bug:
: no known bugs.
Definition at line 174 of file enSwapChain.cpp.
 {
   m_descriptor.outputWindow = window.getHandle();
 }
The documentation for this class was generated from the following files:
C:/Users/Y_Here/Git Repositorios/Graficas Framework [current]/Graphcis_Framework_Neon/Graphcis_Framework_Neon/include/enSwapChain.h
C:/Users/Y_Here/Git Repositorios/Graficas Framework [current]/Graphcis_Framework_Neon/Graphcis_Framework_Neon/src/enSwapChain.cpp