Graphcis Framework: imGuiManager Class Reference
imGuiManager Class Reference
Public Member Functions
~imGuiManager ()
bool Init (enWindow &window)
void beginChildWithFpsCount (float DeltaTime)
void beginFrame (const char *windowName)
for beginning new frames for imGui to draw in
void beginExtraWindow (const char *windowName)
for starting new window in imGui
void addItemCount (std::string_view itemName, uint32 itemCount)
void addButton (std::string_view buttonUse, bool &buttonCondtion)
void addText (std::string_view message, sColorf TextColor={ 1.0f, 1.0f, 1.0f, 1.0f })
void addMultipleText (const std::vector< std::string > &strings)
void addImage (enShaderResourceView &Resoure, uint32 SizeInX=100, uint32 SizeInY=100)
void addSliderFloat (std::string_view NameOfValue, float &Value, float lowerRange=-1.0f, float upperRange=1.0f)
void addCounter (int32_t &CounterValue, std::string_view nameOfValue)
adds 2 buttons used to represent a counter
void addCounter (uint32_t &CounterValue, std::string_view nameOfValue)
adds 2 buttons used to represent a counter
void addCounter (int64_t &CounterValue, std::string_view nameOfValue)
adds 2 buttons used to represent a counter
void addCounter (uint64_t &CounterValue, std::string_view nameOfValue)
adds 2 buttons used to represent a counter
void beginChild (const char *childID)
void endAllChildren ()
void endAllExtraWindows ()
void endExtraWindow ()
void endFrame ()
end and renders the frame
Public Attributes
bool is_initialized { false }
a pointer to a function that opens a file
Private Member Functions
float calculateAverageFPS (float deltaTime)
Private Attributes
uint32 m_childCount
keeps track of how many children the frame has
uint32 m_windowCount
Detailed Description
Definition at line 17 of file imGuiManager.h.
Constructor & Destructor Documentation
~imGuiManager()
imGuiManager::~imGuiManager ()
Highly Important to free the memory
Definition at line 53 of file imGuiManager.cpp.
 {
   if (is_initialized)
   {
   #if DIRECTX
     ImGui_ImplDX11_Shutdown();
     ImGui_ImplWin32_Shutdown();
   #elif OPENGL
     ImGui_ImplOpenGL3_Shutdown();
     ImGui_ImplGlfw_Shutdown();
   #endif // USING_DIRECTX
     ImGui::DestroyContext();
   }
 }
References is_initialized.
Member Function Documentation
addItemCount()
void imGuiManager::addItemCount (std::string_view itemName, uint32 itemCount)
create a child in a frame that will count
Parameters
[in] childId this is the id imGui uses to identify a child
[in] itemName this is the name the user give the item
[in] itemCount how many instances of a certain item exist
Definition at line 180 of file imGuiManager.cpp.
 {
   static std::string messageStr = "Item Name : ";
   // get the data in the string view
   messageStr += itemName.data();
   ig::Text(messageStr.c_str());
   messageStr = "Item Count =  %d";
   ig::TextColored(ImVec4(0.98f, 0.88f, 0.20f, 1.0f), messageStr.c_str(), itemCount);
   // reset the static string
   messageStr = "Item Name : ";
 }
addSliderFloat()
void imGuiManager::addSliderFloat (std::string_view NameOfValue, float & Value, float lowerRange = -1.0f, float upperRange = 1.0f)
add a slider that uses a float to control it
Parameters
Value [in] [out] this is value that the value represent
lowerRange [in]
Definition at line 242 of file imGuiManager.cpp.
 {
   ig::SliderFloat(NameOfValue.data(), &Value, lowerRange, upperRange);
 }
addText()
void imGuiManager::addText (std::string_view message, sColorf TextColor = { 1.0f,1.0f,1.0f,1.0f })
just add a text to the current frame/child
Definition at line 213 of file imGuiManager.cpp.
 {
   ig::TextColored(ImVec4(TextColor.red, TextColor.green, TextColor.blue, TextColor.alpha), message.data());
 }
beginChild()
void imGuiManager::beginChild (const char * childID)
just creates a child for imGui, other methods add functionality
Definition at line 333 of file imGuiManager.cpp.
 {
   m_childCount++;
   ig::BeginChild(childID);
 }
References m_childCount.
beginChildWithFpsCount()
void imGuiManager::beginChildWithFpsCount (float DeltaTime)
set a function pointer to a function that opens file explorer
Parameters
[in] openFileFunc the function that open file explorer
calculates and displays the average fps
Parameters
[in] DeltaTime it's how much time it took to render a frame
Definition at line 106 of file imGuiManager.cpp.
 {
   m_childCount++;
   float averageFps = this->calculateAverageFPS(DeltaTime);
   static const std::string fpsMassage("Average FPS %f");
    //fpsMassage += std::to_string(averageFps);
   ImGui::BeginChild("FPS", ImVec2(420, 130));
   ImGui::Text(fpsMassage.c_str(), averageFps);
 }
References calculateAverageFPS(), and m_childCount.
beginFrame()
void imGuiManager::beginFrame (const char * windowName)
for beginning new frames for imGui to draw in
calls the open file function pointer
Returns
a string which is a path to the opened file
Definition at line 159 of file imGuiManager.cpp.
 {
 #if DIRECTX
   ImGui_ImplDX11_NewFrame();
   ImGui_ImplWin32_NewFrame();
 #elif OPENGL
   ImGui_ImplOpenGL3_NewFrame();
   ImGui_ImplGlfw_NewFrame();
 #endif// DIRECTX
   ImGui::NewFrame();
   ImGui::Begin(windowName);
 }
calculateAverageFPS()
float imGuiManager::calculateAverageFPS (float deltaTime) private
calculates the average fps
Parameters
[in] deltaTime the amount of time that passed
Definition at line 119 of file imGuiManager.cpp.
 {
   // gets the fps
   float const fps = 1.0f / deltaTime;
   // contains the results for later to average them out
   static float fpsTimes[s_fpsSamplesCount] = { 0 };
   static uint32_t  currenFpsIndex = 0;
   if (currenFpsIndex > s_fpsSamplesCount - 1)
   { currenFpsIndex = 0; }
   fpsTimes[currenFpsIndex] = fps;
   currenFpsIndex++;
   float averageFps = 0.0f;
   for (size_t i = 0; i < s_fpsSamplesCount; ++i)
   {
     averageFps += fpsTimes[i];
   }
   return averageFps = averageFps / s_fpsSamplesCount;
 }
endAllChildren()
void imGuiManager::endAllChildren ()
remove all children made by imGuiManager
Definition at line 340 of file imGuiManager.cpp.
 {
   for (uint32 i = 0; i < m_childCount; ++i)
   {
     ig::EndChild();
   }
   m_childCount = 0;
 }
References m_childCount.
endAllExtraWindows()
void imGuiManager::endAllExtraWindows ()
used to remove all the current windows create for ImGui
Definition at line 351 of file imGuiManager.cpp.
 {
   for (uint32 i = 0; i < m_windowCount; ++i)
   {
     ig::End();
   }
   m_windowCount = 0;
 }
endExtraWindow()
void imGuiManager::endExtraWindow ()
used to eliminate individual windows
Definition at line 361 of file imGuiManager.cpp.
 {
   ig::End();
   --m_windowCount;
 }
Init()
bool imGuiManager::Init (enWindow & window)
init the imgui library
Definition at line 69 of file imGuiManager.cpp.
 {
   bool isSuccesful = false;
   is_initialized = IMGUI_CHECKVERSION();
   enDevice& device = enDevice::getInstance();
   enDeviceContext& deviceContext = enDeviceContext::getInstance();
   if (is_initialized)
   {
     ImGui::CreateContext();
     //this can be used to enable or disable opciones
     ImGuiIO& GuiIo = ImGui::GetIO();
     // check for possible error
   #if DIRECTX
     isSuccesful = ImGui_ImplWin32_Init(window.getHandle());
     isSuccesful = ImGui_ImplDX11_Init(device.getInterface(), deviceContext.m_interface);
   #elif OPENGL
     // TODO: REMOVE COMMIT WHEN READY
     isSuccesful = ImGui_ImplGlfw_InitForOpenGL(window.getHandle(), true);
     isSuccesful = ImGui_ImplOpenGL3_Init(s_GlslVersion);
   #endif // USING_DIRECTX
   }
   if (is_initialized)
   {
     ImGui::StyleColorsDark();
   }
   return is_initialized;
 }
References soModule< enDevice >::getInstance(), soModule< enDeviceContext >::getInstance(), and is_initialized.
The documentation for this class was generated from the following files:
C:/Users/Y_Here/Git Repositorios/Graficas Framework [current]/Graphcis_Framework_Neon/Graphcis_Framework_Neon/include/imGuiManager.h
C:/Users/Y_Here/Git Repositorios/Graficas Framework [current]/Graphcis_Framework_Neon/Graphcis_Framework_Neon/src/imGuiManager.cpp